# Generated by Django 3.1 on 2022-11-06 15:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('objectes', django.db.models.manager.Manager()),
            ],
        ),
    ]
