# Generated by Django 3.1 on 2022-11-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='reviev',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='usert',
            new_name='user',
        ),
    ]
